# Основные настройки Loki
loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h  # Хранение логов 30 дней

# Настройки Promtail (исправленный формат без warnings)
promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node_name
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            replacement: $1
            separator: /
            source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
            target_label: job
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
            target_label: __path__
          - action: replace
            regex: true/(.*)
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels: [__meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash, __meta_kubernetes_pod_annotation_kubernetes_io_config_hash, __meta_kubernetes_pod_container_name]
            target_label: __path__

# Настройки Grafana (с актуальным Ingress)
grafana:
  enabled: true
  adminPassword: "admin"  # Замените на свой пароль
  persistence:
    enabled: true
    size: 5Gi
  ingress:
    enabled: true
    ingressClassName: nginx  # Вместо устаревшей аннотации
    hosts:
      - grafana.your-domain.com  # Замените на свой домен
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.your-domain.com

# Настройки Prometheus (если нужен мониторинг метрик)
prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 10Gi