prometheus:
  enabled: true
  isDefault: false
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
  datasource:
    jsonData: "{}"
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  # Sub-chart loki-stack - charts - prometheus - alertmanager
  #https://github.com/prometheus-community/helm-charts/tree/main/charts/alertmanager
  alertmanager:
    enabled: true
    config:
      receivers:
        - name: telepush
          webhook_configs:
            - url: 'https://telepush.dev/api/inlets/alertmanager/2ef978' #URL с токеном после последнего слеша
              http_config:
      route:        
        receiver: 'telepush'
        routes:
         — match:
             severity: critical
           receiver: slack-alert
           continue: true
         — match:
             severity: critical
           receiver: email-alert

loki:
  enabled: true
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: "{}"
    uid: ""

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

grafana:
  enabled: true 
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: 10.0.2
  persistence:
    type: pvc
    enabled: true
    # storageClassName: default
    accessModes:
      - ReadWriteOnce
    size: 3Gi
  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default

  dashboardsConfigMaps:
    default: "grafana-dashboards"

  #dashboards:
  #  default:
  #    custom-dashboard:
  #      file: "grafana-dashboards/6417_rev1 (Kubernetes Cluster (Prometheus)).json"
  #    local-dashboard:
  #      url: "https://raw.githubusercontent.com/Luchik51/otus/refs/heads/logging/grafana-dashboards/747_rev2%20(Kubernetes%20Pod%20Metrics).json"