prometheus:
  enabled: true
  isDefault: false
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
  datasource:
    jsonData: "{}"
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

loki:
  enabled: true
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: "{}"
    uid: ""

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

grafana:
  enabled: true 
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: 10.0.2
  #dashboardProviders:
  # dashboardproviders.yaml:
  #   apiVersion: 1
  #   providers:
  #   - name: 'default'
  #     orgId: 1
  #     folder: ''
  #     type: file
  #     disableDeletion: false
  #     editable: true
  #     options:
  #       path: /var/lib/grafana/dashboards/default

  #dashboardsConfigMaps:
  #  default: "grafana-dashboards"
  dashboards:
    default:
      custom-dashboard:
        file: dashboards/custom-dashboard.json
      local-dashboard:
        url: https://raw.githubusercontent.com/user/repository/master/dashboards/dashboard.json