{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n'transformToGrafanaTable@1.0.0' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.uptime' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n\n[ SWAP bucketizer.last $end $BUCKET_SIZE 1 ] BUCKETIZE\n\nSORT\n\n<%\n  DROP\n  DUP LABELS 'host' GET 'node' STORE\n  { 'node' $node } RELABEL\n%> LMAP \n\n[ 'node' ] 'A' @transformToGrafanaTable",
     "friendlyQuery": {
      "readToken": "",
      "className": "",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 11297071 '__interval' STORE 11297 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n'transformToGrafanaTable@1.0.0' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.uptime' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n\n[ SWAP bucketizer.last $end $BUCKET_SIZE 1 ] BUCKETIZE\n\nSORT\n\n<%\n  DROP\n  DUP LABELS 'host' GET 'node' STORE\n  { 'node' $node } RELABEL\n%> LMAP \n\n[ 'node' ] 'A' @transformToGrafanaTable"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.mem' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n\n[ SWAP bucketizer.mean $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.mem' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n\n[ SWAP bucketizer.mean $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.cpu' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n[ SWAP 0.0 mapper.gt 0 0 0 ] MAP NONEMPTY\n[ SWAP bucketizer.mean $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.cpu' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n[ SWAP 0.0 mapper.gt 0 0 0 ] MAP NONEMPTY\n[ SWAP bucketizer.mean $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\nSORT"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.disk.fs' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n\n[ SWAP bucketizer.mean $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n\n[ 'host' ] '' @renameWithMultipleLabelValues\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.disk.fs' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n\n[ SWAP bucketizer.mean $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n\n[ 'host' ] '' @renameWithMultipleLabelValues\nSORT"
    }
   ]
  },
  {
   "title": "OS Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.load1' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n\n[ SWAP bucketizer.mean $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.load1' \n  { 'host' $nodes }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n\n[ SWAP bucketizer.mean $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Network Input Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE '$node' STORE\n\n[ \n  $token \n  'os.net.dropped' \n  { 'host' $nodes 'direction' 'in' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.sum $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE '$node' STORE\n\n[ \n  $token \n  'os.net.dropped' \n  { 'host' $nodes 'direction' 'in' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.sum $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  },
  {
   "title": "Network Ouput Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE '$node' STORE\n\n[ \n  $token \n  'os.net.dropped' \n  { 'host' $nodes 'direction' 'out' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.sum $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE '$node' STORE\n\n[ \n  $token \n  'os.net.dropped' \n  { 'host' $nodes 'direction' 'out' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.sum $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Network Input Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.net.errs' \n  { 'host' $nodes 'direction' 'in' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n\n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.net.errs' \n  { 'host' $nodes 'direction' 'in' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n\n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  },
  {
   "title": "Network Output Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.net.errs' \n  { 'host' $nodes 'direction' 'out' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n\n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.net.errs' \n  { 'host' $nodes 'direction' 'out' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n\n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Network Input Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.net.packets' \n  { 'host' $nodes 'direction' 'in' 'iface' '~(ens|eth).+' }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.net.packets' \n  { 'host' $nodes 'direction' 'in' 'iface' '~(ens|eth).+' }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  },
  {
   "title": "Network Output Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.net.packets' \n  { 'host' $nodes 'direction' 'out' 'iface' '~(ens|eth).+' }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n[ \n  $token \n  'os.net.packets' \n  { 'host' $nodes 'direction' 'out' 'iface' '~(ens|eth).+' }\n  $end $interval $BUCKET_SIZE 2 * +\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT 2 + ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Network Input Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.net.bytes' \n  { 'host' $nodes 'direction' 'in' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.net.bytes' \n  { 'host' $nodes 'direction' 'in' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  },
  {
   "title": "Network Output Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.net.bytes' \n  { 'host' $nodes 'direction' 'out' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT",
     "friendlyQuery": {
      "readToken": "",
      "className": "sd.rack.v2.",
      "labels": {},
      "bucketizer": null,
      "bucketCount": 50,
      "reducer": null,
      "reducerLabels": [],
      "filter": null,
      "filterLabels": [],
      "filterParamNumber": 0,
      "filterParamMap": {},
      "filterParamClass": "",
      "bucketizers": [
       "sum",
       "max",
       "min",
       "mean",
       "mean.circular",
       "bucketizer.mean.circular.exclude-nulls",
       "first",
       "last",
       "join",
       "median",
       "count",
       "and",
       "or"
      ],
      "reducers": [
       "argmax",
       "argmin",
       "count",
       "count.exclude-nulls",
       "count.include-nulls",
       "join",
       "join.forbid-nulls",
       "max",
       "max.forbid-nulls",
       "mean",
       "mean.exclude-nulls",
       "mean.circular",
       "mean.circular.exclude-nulls",
       "median",
       "min",
       "min.forbid-nulls",
       "and",
       "and.exclude-nulls",
       "or",
       "or.exclude-nulls",
       "sd",
       "shannonentropy.0",
       "shannonentropy.1",
       "sum",
       "sum.forbid-nulls",
       "var"
      ],
      "filters": [
       { "name": "byclass", "type": "S" },
       { "name": "bylabels", "type": "M" },
       { "name": "last.eq", "type": "N" },
       { "name": "last.ne", "type": "N" },
       { "name": "last.gt", "type": "N" },
       { "name": "last.ge", "type": "N" },
       { "name": "last.lt", "type": "N" },
       { "name": "last.le", "type": "N" }
      ]
     },
     "ws": "1552276358129000 'start' STORE '2019-03-11T03:52:38.129Z' 'startISO' STORE 1552297958129000 'end' STORE '2019-03-11T09:52:38.129Z' 'endISO' STORE 21600000000 'interval' STORE 22594142 '__interval' STORE 22594 '__interval_ms' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' '$token' STORE 'ZZIXbDNEACOo5a4RhUID9uTXNwQ.A0tfmbDmydjIrtBISU3N4VdpzjhoI9mfdkV4S0wGZdSZkZefjbn_S1U77jd4ozKWX2wxfVcWaGCm56mxvb4HSPBjNl.BNQyA2.Ci3NOYbpU78Xpw3syc0.2sGAZnvG9AXbpS' 'token' STORE '~.*' 'nodes' STORE \n$interval $__interval / 10 / 'BUCKET_COUNT' STORE\n$interval $BUCKET_COUNT / 'BUCKET_SIZE' STORE\n\n'renameWithMultipleLabelValues@1.0.0' FIMPORT\n'grafanaMultiVariable@1.0.1' FIMPORT\n\n\n$nodes @grafanaMultiVariable 'All' '~.*' REPLACE 'nodes' STORE\n\n\n[ \n  $token \n  'os.net.bytes' \n  { 'host' $nodes 'direction' 'out' 'iface' '~(ens|eth).+' }\n  $end $interval\n]\nFETCH \n[ SWAP mapper.delta 1 0 0 ] MAP\n\n[ SWAP bucketizer.last $end $BUCKET_SIZE $BUCKET_COUNT ] BUCKETIZE\n\n[ 'host' ] '' @renameWithMultipleLabelValues\n\nSORT"
    }
   ]
  }
 ]
}