{
 "title": "Kubernetes Node Stats",
 "description": "Kubernetes Nodes Stats via Prometheus. A fork of 8171 preferring node name to IP address.\r\n",
 "tags": [
  "nodes",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": "label_values(kubernetes_node)" }
  ]
 },
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", kubernetes_node=\"$node\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{kubernetes_node=\"$node\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{kubernetes_node=\"$node\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{kubernetes_node=\"$node\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=\"$node\"} - node_memory_MemFree_bytes{kubernetes_node=\"$node\"} - node_memory_Buffers_bytes{kubernetes_node=\"$node\"} - node_memory_Cached_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{kubernetes_node=\"$node\"} - node_memory_MemFree_bytes{kubernetes_node=\"$node\"}  - node_memory_Buffers_bytes{kubernetes_node=\"$node\"} - node_memory_Cached_bytes{kubernetes_node=\"$node\"}) / node_memory_MemTotal_bytes{kubernetes_node=\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_node) (rate(node_nfsd_disk_bytes_read_total{kubernetes_node=\"$node\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (kubernetes_node) (rate(node_nfsd_disk_bytes_written_total{kubernetes_node=\"$node\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (kubernetes_node) (rate(node_disk_io_time_seconds_total{kubernetes_node=\"$node\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_node=\"$node\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",kubernetes_node=\"$node\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_node=\"$node\"})"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{kubernetes_node=\"$node\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{kubernetes_node=\"$node\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}