{
 "title": "Nextcloud логи",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Авторизации",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"nextcloud\"} |= `GET /avatar/`"
    }
   ]
  },
  {
   "title": "Не удачные авторизации",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"nextcloud\"} |= `GET /login?direct=1&user=`"
    }
   ]
  },
  {
   "title": "Правка файлов",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{app=\"nextcloud\"} |= `207 148`"
    }
   ]
  }
 ]
}