name: Deploy Nextcloud AIO to Yandex Kubernetes

on:
  push:
    branches: [ main ]

env:
  YC_CLUSTER_NAME: "nextcloud-k8s"
  YC_NETWORK_NAME: "default"
  YC_SUBNET_NAME: "default-ru-central1-a"
  YC_K8S_VERSION: "1.30"
  YC_NODE_COUNT: "2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка YC CLI
    #source "/home/luchik/.bashrc"
    - name: Install YC CLI
      run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a 
        sudo apt-get install -y jq       
        echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH 

    # Аутентификация в Yandex Cloud
    - name: Configure YC CLI
      run: |
        yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
        yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
        echo '${{ secrets.YC_SA_KEY }}' | jq -r . > key.json  # Фикс здесь!
        yc config set service-account-key key.json
        rm -f key.json

    # Проверка Аутентификация в Yandex Cloud
    - name: Configure YC CLI
      run: |
        $FOLDER_ID = yc config get folder-id
        echo $FOLDER_ID

    # Создание Kubernetes-кластера
    - name: Create Yandex Managed Kubernetes Cluster
      run: |
        yc managed-kubernetes cluster create
          --name ${{ env.YC_CLUSTER_NAME }} \
          --network-name yc-auto-network \
          --zone ru-central1-a \
          --subnet-name yc-auto-subnet-0 \
          --public-ip \
          --service-account-id aje7f88hqas3q35b9msq \
          --node-service-account-id ajenidupv100n3qr1kl1

    # Создание Kubernetes-кластера
    - name: Create Yandex Managed Kubernetes Cluster
      run: |
        yc managed-kubernetes cluster create \
          --name ${{ env.YC_CLUSTER_NAME }} \
          --network-name ${{ env.YC_NETWORK_NAME }} \
          --zone ru-central1-a \
          --subnet-name ${{ env.YC_SUBNET_NAME }} \
          --public-ip \
          --version ${{ env.YC_K8S_VERSION }} \
          --node-count ${{ env.YC_NODE_COUNT }} \
          --standard \
          --platform-id standard-v2 \
          --memory 4 \
          --cores 2 \
          --core-fraction 100 \
          --disk-type network-ssd \
          --disk-size 50 \
          --service-account-name default \
          --node-service-account-name default

    # Создание node-group для Kubernetes-кластера
    - name: Create Yandex Managed Kubernetes Cluster node-group
      run: |
        yc managed-kubernetes node-group create \
          --name k8s-demo-ng `
          --cluster-name k8s-demo `
          --platform standard-v3 `
          --cores 2 `
          --memory 4 `
          --core-fraction 50 `
          --disk-type network-ssd `
          --fixed-size 2 `
          --network-interface subnets=yc-auto-subnet-0,ipv4-address=nat,security-group-ids=[<идентификаторы_групп_безопасности>] `
          --async

    # Получение kubeconfig
    - name: Get Kubeconfig
      run: |
        yc managed-kubernetes cluster get-credentials ${{ env.YC_CLUSTER_NAME }} --external
        kubectl config view --raw > kubeconfig.yaml

    # Установка Helm
    - name: Install Helm
      uses: azure/setup-helm@v3

    # Установка Nextcloud AIO
    - name: Deploy Nextcloud AIO
      run: |
        helm repo add nextcloud-aio https://nextcloud.github.io/all-in-one/
        helm upgrade --install nextcloud-aio nextcloud-aio/nextcloud-aio-helm-chart \
          --namespace nextcloud \
          --create-namespace \
          --set ingress.enabled=true \
          --set ingress.hosts[0].host=nextcloud.example.com \
          --set ingress.hosts[0].paths[0].path="/" \
          --set ingress.hosts[0].paths[0].pathType=Prefix

    # Получение внешнего IP (опционально)
    - name: Get Nextcloud External IP
      run: |
        kubectl get svc -n nextcloud